---
title: "R Notebook"
output: html_notebook
---

## Load merged gene symbol + ENSG mapping file and PMTL file
```{r}
library(tidyverse)

ens_map <- read_tsv("results/gencode_ensg_symbol_map_merged.tsv") %>%
  dplyr::rename(ensg_id = ensembl)
pmtl <- read_tsv("input/PMTL_v1.1.tsv") %>%
  dplyr::rename(ensg_id = Ensembl_ID, pmtl = FDA_Designation)
# add pmtl version
pmtl$version <- "PMTL version 1.1"
```
## Are there all PMTL ensg ids included in the mapping file? 
```{r}
setdiff(pmtl$ensg_id, ens_map$ensg_id)
#yes
```

##Merge the PMTL file with ENSG mapping file
```{r}
ens_pmtl_mer <- merge(pmtl, ens_map, all.x = T)

# Do any gene IDs mismatch?
ens_pmtl_mer$mismatches <- ifelse(ens_pmtl_mer$Approved_Symbol == ens_pmtl_mer$gene_symbol, "true", "false")
table(ens_pmtl_mer$mismatches)
ens_pmtl_mer %>% 
  filter(mismatches == "false") %>%
  dplyr::select(ensg_id, Approved_Symbol, gene_symbol)
```
## Keep the `gene_symbol` as in the RNA-Seq files
```{r}
pmtl <- pmtl %>%
  mutate(gene_symbol = Approved_Symbol)


# Cases where gene_symbol has not changed
gs_no_update <- ens_map %>%
  full_join(pmtl) %>%
  dplyr::select(ensg_id, gene_symbol, pmtl, version) %>%
  distinct() %>%
  filter(!ensg_id == "Symbol_Not_Found" | !gene_symbol == 'NA') %>%
  mutate_at(c('version'), ~replace_na(.,"NA")) %>%
  left_join(
    x = dplyr::filter(., version != "v39")
    , y = dplyr::filter(., version == "v39")
    , by = c("ensg_id")
  ) %>%
  mutate(latest_gene_symbol = ifelse(!is.na(gene_symbol.y), gene_symbol.y, gene_symbol.x)) %>%
  mutate(previous_gene_symbol = gene_symbol.x) %>%
  dplyr::select(ensg_id,gene_symbol.x,pmtl.x,latest_gene_symbol,previous_gene_symbol) %>%
  distinct() %>%
  mutate(duplicates = if_else(latest_gene_symbol == previous_gene_symbol ,
                              TRUE,
                              FALSE)) %>%
  mutate_at(c('duplicates'), ~replace_na(.,TRUE)) %>%
  filter(duplicates == TRUE) %>%
  mutate(gene_symbol= gene_symbol.x, pmtl=pmtl.x) %>%
  dplyr::select(ensg_id,gene_symbol, pmtl, latest_gene_symbol)

# Cases where gene_symbol has changed
gs_updated <- ens_map %>%
  full_join(pmtl) %>%
  dplyr::select(ensg_id, gene_symbol, pmtl, version) %>%
  distinct() %>%
  filter(!ensg_id == "Symbol_Not_Found" | !gene_symbol == 'NA') %>%
  mutate_at(c('version'), ~replace_na(.,"NA")) %>%
  left_join(
    x = dplyr::filter(., version != "v39")
    , y = dplyr::filter(., version == "v39")
    , by = c("ensg_id")
  ) %>%
  mutate(latest_gene_symbol = gene_symbol.y) %>%
  mutate(previous_gene_symbol = gene_symbol.x) %>%
  dplyr::select(ensg_id,gene_symbol.x,pmtl.x,latest_gene_symbol,previous_gene_symbol) %>%
  distinct() %>%
  mutate(duplicates = if_else(latest_gene_symbol == previous_gene_symbol ,
                              TRUE,
                              FALSE)) %>%
  mutate_at(c('duplicates'), ~replace_na(.,TRUE)) %>%
  filter(duplicates == FALSE) %>%
  mutate(gene_symbol= gene_symbol.x, pmtl=pmtl.x) %>%
  dplyr::select(ensg_id,gene_symbol, pmtl, latest_gene_symbol) 


ens_hugo_pmtl <- rbind(gs_no_update, gs_updated) %>%
  distinct() %>%
  write_tsv("results/ensg-hugo-pmtl-mapping.tsv")

```


